---
title       : 'Praat'
author      : 'Joseph V. Casillas, PhD'
---

```{r, libs, echo=F, message=F, warning=F}
library("stringr")
```

## Overview

This is a collection of tutorials and scripts for working in Praat. 

</br> 

## Scripts

```{r echo = F, results = 'asis', cache=FALSE}
script_paths <- dir('./site_libs/assets/scripts', full = T, pattern = ".praat")
script_names <- dir('./site_libs/assets/scripts', full = F, pattern = ".praat") %>% 
  str_remove(., ".praat")
links   <- paste0("- ", "[", script_names , "]", "(", script_paths, ")")
writeLines(links)
```

</br>

## Slides

```{r echo = F, results = 'asis'}
slide_names <- dir('slides', full = TRUE)
slide_links <- paste0("- ", "[", basename(slide_names), "]", "(", 
                      slide_names, "/index.html)")
total  <- length(slide_links)
keep   <- total - 3

writeLines(slide_links[1:keep])
```

</br>

## Misc

### Links

- [Praat official website](http://www.fon.hum.uva.nl/praat/)
- Los sonidos del habla - Universidad de Iowa ([inglés](http://soundsofspeech.uiowa.edu/english/english.html), [español](http://soundsofspeech.uiowa.edu/spanish/spanish.html))

</br> 

### Articles

- Coming soon


</br> 


## References

- Coming soon

```{r, eval=TRUE, echo=FALSE, cache=FALSE}
library(RefManageR)
bib <- ReadBib("./site_libs/assets/refs/phon340bib.bib", check = FALSE)
```


```{r, results='asis', echo=FALSE, eval=FALSE}
ui <- "-"
writeLines(ui); print(bib[key = "Colina"], .opts = list(check.entries = FALSE, 
					  style = "html", bib.style = "authoryear"))
writeLines(ui); print(bib[key = "ILH2011"], .opts = list(check.entries = FALSE, 
					  style = "html", bib.style = "authoryear"))
writeLines(ui); print(bib[key = "Olarrea"], .opts = list(check.entries = FALSE, 
					  style = "html", bib.style = "authoryear"))
writeLines(ui); print(bib[key = "Schwegler"], .opts = list(check.entries = FALSE, 
					  style = "html", bib.style = "authoryear"))
writeLines(ui); print(bib[key = "cOral"], .opts = list(check.entries = FALSE, 
					  style = "html", bib.style = "authoryear"))
```

</br></br>






